### ISSUE TITLE
Panics are caught by the golang http server instead of the Pace error handler

### ISSUE THREAD

**Issue by gabrielruiu** [pace/bricks#113]
The pace Router object registers an error handler that normally intercepts panics:

```
// HandleRequest should be called with defer to recover panics in request handlers
func HandleRequest(handlerName string, w http.ResponseWriter, r *http.Request) {
	if rp := recover(); rp != nil {
		HandleError(&PanicWrap{rp}, handlerName, w, r)
	}
}
```
But panics are caught instead by the golang http server:
http/server.go
```
// Serve a new connection.
func (c *conn) serve(ctx context.Context) {
	c.remoteAddr = c.rwc.RemoteAddr().String()
	ctx = context.WithValue(ctx, LocalAddrContextKey, c.rwc.LocalAddr())
	defer func() {
		if err := recover(); err != nil && err != ErrAbortHandler {
			const size = 64 << 10
			buf := make([]byte, size)
			buf = buf[:runtime.Stack(buf, false)]
			c.server.logf("http: panic serving %v: %v\n%s", c.remoteAddr, err, buf)
		}
```

Because of this, the `recover()` function in `HandleRequest` is always nil.

**Comment by threez** [comment]
Hmm, looks odd. I have seen panics in our logs at times, why do you think that is the case, can you make a change to the testserver to showcase the error?

**Comment by gabrielruiu** [comment]
Testserver behaves the same. When performing a request on the `/panic` endpoint, the panic is picked up by the go native http server, not the `recoveryHandler`.

Not sure if it's relevant, but Im using go `1.13.1`

**Comment by gabrielruiu** [comment]
Panics are indeed logged though:

```
2019-11-06 11:17:57 |????| [http.Server] http: panic serving [::1]:40624: Test for sentry
goroutine 549 [running]:
net/http.(*conn).serve.func1(0xc0000fdf40)
        /home/gruiu/programs/go-1.13.1/go/src/net/http/server.go:1767 +0x149
panic(0xc84f40, 0xe9e160)
        /home/gruiu/programs/go-1.13.1/go/src/runtime/panic.go:679 +0x1e0
main.main.func2(0x7f079953d8c0, 0xc0001bc3c0, 0xc0001ec600)
        /home/gruiu/workspace/misc/bricks/tools/testserver/main.go:84 +0x5b
net/http.HandlerFunc.ServeHTTP(0xe016b0, 0x7f079953d8c0, 0xc0001bc3c0, 0xc0001ec600)
        /home/gruiu/programs/go-1.13.1/go/src/net/http/server.go:2007 +0x44
github.com/pace/bricks/maintenance/tracing.(*traceHandler).ServeHTTP(0xc000184870, 0x7f079953d8c0, 0xc0001bc380, 0xc0001ec400)
        /home/gruiu/workspace/misc/bricks/maintenance/tracing/tracing.go:74 +0x956
github.com/rs/zerolog/hlog.RequestIDHandler.func1.1(0x7f079953d8c0, 0xc0001bc380, 0xc0001ec400)
        /home/gruiu/workspace/misc/bricks/vendor/github.com/rs/zerolog/hlog/hlog.go:164 +0x29f
net/http.HandlerFunc.ServeHTTP(0xc0001bc340, 0x7f079953d8c0, 0xc0001bc380, 0xc0001ec300)
        /home/gruiu/programs/go-1.13.1/go/src/net/http/server.go:2007 +0x44
github.com/rs/zerolog/hlog.AccessHandler.func1.1(0xeb3980, 0xc0001240a0, 0xc0001ec300)
        /home/gruiu/workspace/misc/bricks/vendor/github.com/rs/zerolog/hlog/hlog.go:175 +0x119
net/http.HandlerFunc.ServeHTTP(0xc000124020, 0xeb3980, 0xc0001240a0, 0xc0001ec300)
        /home/gruiu/programs/go-1.13.1/go/src/net/http/server.go:2007 +0x44
github.com/rs/zerolog/hlog.NewHandler.func1.1(0xeb3980, 0xc0001240a0, 0xc0001ec300)
        /home/gruiu/workspace/misc/bricks/vendor/github.com/rs/zerolog/hlog/hlog.go:30 +0x239
net/http.HandlerFunc.ServeHTTP(0xc00011e070, 0xeb3980, 0xc0001240a0, 0xc0001ec200)
        /home/gruiu/programs/go-1.13.1/go/src/net/http/server.go:2007 +0x44
github.com/pace/bricks/maintenance/errors.(*recoveryHandler).ServeHTTP(0xc000124040, 0xeb3980, 0xc0001240a0, 0xc0001ec200)
        /home/gruiu/workspace/misc/bricks/maintenance/errors/error.go:39 +0xc2
github.com/pace/bricks/http.metricsMiddleware.func1(0xeb4e80, 0xc00040eb60, 0xc0001ec200)
        /home/gruiu/workspace/misc/bricks/http/metrics.go:73 +0x194
net/http.HandlerFunc.ServeHTTP(0xc000124080, 0xeb4e80, 0xc00040eb60, 0xc0001ec200)
        /home/gruiu/programs/go-1.13.1/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000fbd50, 0xeb4e80, 0xc00040eb60, 0xc0001ec200)
        /home/gruiu/workspace/misc/bricks/vendor/github.com/gorilla/mux/mux.go:162 +0x25a
net/http.serverHandler.ServeHTTP(0xc0004876c0, 0xeb4e80, 0xc00040eb60, 0xc000248000)
        /home/gruiu/programs/go-1.13.1/go/src/net/http/server.go:2802 +0x20f
net/http.(*conn).serve(0xc0000fdf40, 0xeb6480, 0xc000084400)
        /home/gruiu/programs/go-1.13.1/go/src/net/http/server.go:1890 +0x1716
created by net/http.(*Server).Serve
        /home/gruiu/programs/go-1.13.1/go/src/net/http/server.go:2927 +0x911
```

**Comment by gabrielruiu** [comment]
Not sure what I did different/wrong, but now it seems the panic is picked up by the `recoveryHandler`, as it should. I don't know what circumstances lead to the initial misbehavior.
